ALTER TABLE "public"."stages" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."topics" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."topic_resources" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."projects" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."skills" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."topic_skills" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."project_skills" ENABLE ROW LEVEL SECURITY;
